package: minibar_time_track
version: '1.0.0-beta1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
requires:
    packages:
        minibar: '>2.0.0'
    redaxo: '^5.17.1'
    php:
        version: '>=8.1, <9'
